---
version: '3'
services:
  mysql:
    image: mysql:5.7
    volumes:
      mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=icescrum
      - MYSQL_ROOT_PASSWORD=myPass
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  icescrum:
    image: nicholaswilde/icescrum
    volumes:
      root:/root
    ports:
      - "8080:8080"
    depends_on:
      - mysql
volumes:
  root:
  mysql:
